name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # lub inna gałąź

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install  # lub yarn install
          npm run build  # komenda do budowania projektu

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git subtree push --prefix path/to/subfolder origin gh-pages
